### ISSUE TITLE
No Multitenancy resource in the menu

### ISSUE THREAD

**Issue by Dontorpedo** [romegasoftware/MultitenancyNovaTool#12]
Hi, your documentation says:

> items labelled "Multitenancy" and "Roles & Permissions" will appear in your Nova app after installation

but i see only Roles & Permissions, there is no Multitenancy in the menu, i dublechecked the installationssteps, but no result.

i use: Nova  v3.5.0 
Laravel 7
php: 7.2

**Comment by Naoray** [comment]
Did you login with a `Super Administrator`?

**Comment by Dontorpedo** [comment]
HA, thanks!

I am on laragon..

had to put the admin address into the hostfile and login within it.. now it works..

thanks!
